name: Set up project
description: Set up JDK 17 and Gradle

runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set up gradle
      run: ./gradlew help
