name: Build apps debug and release

on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildApps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up gradle
        run: ./gradlew help
      - name: Build debug mobile app
        run: ./gradlew :app:assembleDebug
      - name: Build release mobile app
        run: ./gradlew :app:assembleRelease
      - name: Build debug wearable app
        run: ./gradlew :wearable:assembleDebug
      - name: Build release wearable app
        run: ./gradlew :wearable:assembleRelease
