name: Set up project

on:
  workflow_call:

jobs:
  setUpProject:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up gradle
        run: ./gradlew help
