name: Static code analysis

on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  staticAnalysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/set-up.yml
        # Execute static code analysis
      - name: Check
        run: ./gradlew check -x test
